In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
arr_1d[0]

np.int64(1)

In [3]:
print(arr_1d[0])

1


In [4]:
a = [1, 2, 3, 4, 5]
a[0]

1

In [5]:
print(arr_1d[2])

3


In [6]:
print(arr_1d[-1])

5


In [7]:
arr_2d = np.array([
                    [1, 2, 3],
                    [4, 5, 7],
                    [6, 8, 9],
                    [11, 17, 19]
])

In [8]:
print(arr_2d[0, 0])

1


In [9]:
print(arr_2d[-4, -3])

1


In [10]:
print(arr_2d[2, 1])

8


In [14]:
# 슬라이싱

arr_1d = np.array([1, 2, 3, 4, 5])

arr_1d[0:2]

print(arr_1d[0:2])
print(arr_1d[1:2])
print(arr_1d[:4])
print(arr_1d[:5])

[1 2]
[2]
[1 2 3 4]
[1 2 3 4 5]


In [16]:
arr_2d = np.array([
            [1, 2, 3, 5],
            [1, 3, 5, 7],
            [2, 4, 6, 8],
            [7, 11, 13, 17]
])

print(arr_2d[0:4])
print(arr_2d[0:4, 0])
print(arr_2d[0:4, 1])

[[ 1  2  3  5]
 [ 1  3  5  7]
 [ 2  4  6  8]
 [ 7 11 13 17]]
[1 1 2 7]
[ 2  3  4 11]


In [17]:
print(arr_2d[ :4, 0])

[1 1 2 7]


In [18]:
print(arr_2d[ : , 0])

[1 1 2 7]


In [19]:
arr_2d = np.array([
            [1, 2, 3, 5],
            [1, 3, 5, 7],
            [2, 4, 6, 8],
            [7, 11, 13, 17]
])
print(arr_2d[0:3, 0:3])

[[1 2 3]
 [1 3 5]
 [2 4 6]]


In [20]:
print(arr_2d[:3, :3])

[[1 2 3]
 [1 3 5]
 [2 4 6]]


In [21]:
print(arr_2d[ :-1, :-1])

[[1 2 3]
 [1 3 5]
 [2 4 6]]


In [22]:
arr_2d = np.array([
            [1, 2, 3, 5],
            [1, 3, 5, 7],
            [2, 4, 6, 8],
            [7, 11, 13, 17]
])
type(arr_2d)

numpy.ndarray

In [23]:
print(arr_2d[1:3, 1:3 ])

[[3 5]
 [4 6]]


In [26]:
print(arr_2d[-3:-1, -3:-1])
print(arr_2d[1:-1, 1:-1])

[[3 5]
 [4 6]]
[[3 5]
 [4 6]]


In [28]:
print(arr_2d[1:3, 0:4])
print(arr_2d[1:3, :])
print(arr_2d[1:-1, :])

[[1 3 5 7]
 [2 4 6 8]]
[[1 3 5 7]
 [2 4 6 8]]
[[1 3 5 7]
 [2 4 6 8]]


In [31]:
arr_2d = np.array([
            [1, 2, 3, 5],
            [1, 3, 5, 7],
            [2, 4, 6, 8],
            [7, 11, 13, 17]
])

print(arr_2d[3, 0:4])
print(arr_2d[3, :])
print(arr_2d[-1, :])

[ 7 11 13 17]
[ 7 11 13 17]
[ 7 11 13 17]


In [36]:
arr_2d = np.array([
            [1, 2, 3, 5],
            [1, 3, 5, 7],
            [2, 4, 6, 8],
            [7, 11, 13, 17]
])

print(arr_2d[2:4, 2:4])
print(arr_2d[2:, 2:])
print(arr_2d[-2:, -2:])

[[ 6  8]
 [13 17]]
[[ 6  8]
 [13 17]]
[[ 6  8]
 [13 17]]


In [37]:
# ndarray 원소별 연산

arr = np.array([0, 1, -4, -16, 25])
print(arr)

[  0   1  -4 -16  25]


In [38]:
arr_abs = np.abs(arr)

print(arr_abs)

[ 0  1  4 16 25]


In [39]:
arr_fabs = np.fabs(arr)
print(arr_fabs)

[ 0.  1.  4. 16. 25.]


In [40]:
arr_sort = np.sqrt(arr)
print(arr)
print(arr_sort)

[  0   1  -4 -16  25]
[ 0.  1. nan nan  5.]


C:\Users\as4761285 001\AppData\Local\Temp\ipykernel_6160\3107810229.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr_sort = np.sqrt(arr)


In [41]:
arr_square = np.square(arr)
print(arr)
print(arr_square)

[  0   1  -4 -16  25]
[  0   1  16 256 625]


In [42]:
arr_exp = np.exp(arr)
print(arr)
print(arr_exp)

[  0   1  -4 -16  25]
[1.00000000e+00 2.71828183e+00 1.83156389e-02 1.12535175e-07
 7.20048993e+10]


In [44]:
arr_log = np.log(arr)
print(arr)
print(arr_log)

[  0   1  -4 -16  25]
[      -inf 0.                nan        nan 3.21887582]


C:\Users\as4761285 001\AppData\Local\Temp\ipykernel_6160\4217760339.py:1: RuntimeWarning: divide by zero encountered in log
  arr_log = np.log(arr)
C:\Users\as4761285 001\AppData\Local\Temp\ipykernel_6160\4217760339.py:1: RuntimeWarning: invalid value encountered in log
  arr_log = np.log(arr)


In [45]:
arr_log10 = np.log10(arr)
print(arr)
print(arr_log10)

[  0   1  -4 -16  25]
[      -inf 0.                nan        nan 1.39794001]


C:\Users\as4761285 001\AppData\Local\Temp\ipykernel_6160\784130791.py:1: RuntimeWarning: divide by zero encountered in log10
  arr_log10 = np.log10(arr)
C:\Users\as4761285 001\AppData\Local\Temp\ipykernel_6160\784130791.py:1: RuntimeWarning: invalid value encountered in log10
  arr_log10 = np.log10(arr)


In [49]:
arr = np.array([1.15, -2.33, 3.557, -4.095])

arr_round = np.round(arr)
print(arr)
print(arr_round)

[ 1.15  -2.33   3.557 -4.095]
[ 1. -2.  4. -4.]


In [50]:
arr_round_1 = np.round(arr, 1)
print(arr)
print(arr_round_1)

[ 1.15  -2.33   3.557 -4.095]
[ 1.2 -2.3  3.6 -4.1]


In [51]:
arr_round_c = np.ceil(arr)
print(arr)
print(arr_round_c)

[ 1.15  -2.33   3.557 -4.095]
[ 2. -2.  4. -4.]


In [52]:
arr_trunc = np.trunc(arr)
print(arr)
print(arr_trunc)

[ 1.15  -2.33   3.557 -4.095]
[ 1. -2.  3. -4.]


In [54]:
arr_1 = np.arange(5)
print(arr_1)

[0 1 2 3 4]


In [55]:
arr_2 = np.arange(1, 10, step=2)
print(arr_2)

[1 3 5 7 9]


In [56]:
arr_add_1 = np.add(arr_1, arr_2)
print(arr_1)
print(arr_2)
print(arr_add_1)

[0 1 2 3 4]
[1 3 5 7 9]
[ 1  4  7 10 13]


In [58]:
a_1 = list(range(5))
a_2 = list(range(1, 10, 2))
a_add_2= a_1 + a_2
print(a_add_2)

[0, 1, 2, 3, 4, 1, 3, 5, 7, 9]


In [60]:
arr_subtract_1 = np.subtract(arr_1, arr_2)
print(arr_1)
print(arr_2)
print(arr_subtract_1)

[0 1 2 3 4]
[1 3 5 7 9]
[-1 -2 -3 -4 -5]


In [61]:
arr_1 - arr_2

array([-1, -2, -3, -4, -5])

In [62]:
arr_mul = np.multiply(arr_1, arr_2)
print(arr_mul)

[ 0  3 10 21 36]


In [63]:
arr_1 * arr_2

array([ 0,  3, 10, 21, 36])

In [64]:
arr_divide = np.divide(arr_1, arr_2)
arr_divide

array([0.        , 0.33333333, 0.4       , 0.42857143, 0.44444444])

In [65]:
arr_1 / arr_2

array([0.        , 0.33333333, 0.4       , 0.42857143, 0.44444444])

In [66]:
np.mod(arr_1, arr_2)

array([0, 1, 2, 3, 4])

In [67]:
arr_1 % arr_2

array([0, 1, 2, 3, 4])

In [68]:
np.power(arr_1, arr_2)

array([     0,      1,     32,   2187, 262144])

In [69]:
arr_1 ** arr_2

array([     0,      1,     32,   2187, 262144])

In [70]:
arr_1d_3 = np.array([1, 2, 3])
print(arr_1d_3)

[1 2 3]


In [71]:
arr_1d_1 = np.array([5])
print(arr_1d_1)
print(arr_1d_1.shape)

[5]


In [72]:
arr_add = arr_1d_3 + arr_1d_1
print(arr_add)

[6 7 8]


In [73]:
arr_2d_3X3 = np.array([
            [1, 4, 7],
            [2, 5, 6],
            [3, 6, 9]
])
arr_2d_3X3

array([[1, 4, 7],
       [2, 5, 6],
       [3, 6, 9]])

In [ ]:
array([[1, 4, 7],
       [2, 5, 6],
       [3, 6, 9]])

arr_1d_3 = np.array([1, 0, -1])
arr_1d_3

In [77]:
arr_add = arr_2d_3X3 + arr_1d_3
print(arr_add)

[[ 2  6 10]
 [ 3  7  9]
 [ 4  8 12]]


In [80]:
arr_2d_1X3 = np.array([[1, 2, 3]])

print(arr_2d_1X3)
print(arr_2d_1X3.shape)
print(arr_2d_1X3.ndim)


[[1 2 3]]
(1, 3)
2


In [82]:
arr_2d_3X1 = np.array([
            [1],
            [0],
            [-1]
])
print(arr_2d_3X1)
print(arr_2d_3X1.shape)
print(arr_2d_3X1.ndim)

[[ 1]
 [ 0]
 [-1]]
(3, 1)
2


In [84]:
arr_2d_add = arr_2d_1X3 + arr_2d_3X1
print(arr_2d_1X3)
print(arr_2d_3X1)
print(arr_2d_add)

[[1 2 3]]
[[ 1]
 [ 0]
 [-1]]
[[2 3 4]
 [1 2 3]
 [0 1 2]]
