In [1]:
import numpy as np

In [2]:
arr_1d = np.arange(8) #[0, 1, 2 ... 7]
print(arr_1d)

[0 1 2 3 4 5 6 7]


In [3]:
arr_2d_2X4 = arr_1d.reshape(2, 4)
print(arr_2d_2X4)

[[0 1 2 3]
 [4 5 6 7]]


In [4]:
arr_2d_4X2 = arr_1d.reshape(4, 2)
print(arr_2d_4X2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [5]:
arr_1d = np.arange(9)
print(arr_1d)

[0 1 2 3 4 5 6 7 8]


In [6]:
arr_2d_3X3 = arr_1d.reshape(3, 3)
print(arr_2d_3X3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
arr_2d_3Xn = arr_1d.reshape(3, -1)
print(arr_2d_3Xn)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
arr_2d_nx3 = arr_1d.reshape(-1 , 3)
print(arr_2d_nx3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
arr1 = np.array([[0, 1, 2],
          [3, 4, 5],
          [6, 7, 8]])
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
arr2 = np.arange(9).reshape(3, 3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
# 3차원 배열
arr4 = np.arange(12).reshape(3, 2, 2)
print(arr4)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [13]:
arr5 = np.arange(12).reshape(3, 2, -1)
print(arr5)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [14]:
arr6 = np.arange(12).reshape(-1, 2, 2)
print(arr6)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [15]:
arr_1d = arr1.reshape(9)
print(arr_1d)

[0 1 2 3 4 5 6 7 8]


In [16]:
arr4_1d = arr4.reshape(12)
print(arr4_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [18]:
arr2_1d = arr2.ravel()
print(arr2_1d)

[0 1 2 3 4 5 6 7 8]


In [19]:
arr4_1d = arr4.flatten()
print(arr4_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [20]:
arr_2d = np.arange(8).reshape(4, 2)
print(arr_2d)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [21]:
arr_2d_T = arr_2d.transpose()
print(arr_2d_T)

[[0 2 4 6]
 [1 3 5 7]]
